blank_issues_enabled: false
contact_links:
  - name: Dokumentacja i Architektura StageSync
    url: https://github.com/Negatywistczny/stagesync/tree/main/docs
    about: Zapoznaj się z dokumentacją techniczną projektu.
