export {
  DEFAULT_PPQ,
  assertValidTimeSignature,
  ticksPerBar,
  localTicksPerBeat,
  ticksPerMs,
  elapsedToTicks,
  ticksToMs,
  ticksToBbt,
  bbtToTicks,
  toDisplayBar,
  fromDisplayBar,
  quartersToTicks,
  ticksToQuarters,
  absBeatToTicks,
  type TimeSignature,
  type Bbt,
} from "./time.js";

export {
  resolveMeterAtTicks,
  ticksToBbtAlongMeterMap,
  bbtToTicksAlongMeterMap,
  type MeterMapEvent,
} from "./meter-map-bbt.js";

export {
  LibrarySchema,
  LibraryProjectEntrySchema,
  BPM_MIN,
  BPM_MAX,
  BpmSchema,
  ProjectIdSchema,
  FormaClipKindSchema,
  FormaClipSchema,
  TempoEventSchema,
  MeterEventSchema,
  KeySignatureSchema,
  KeyEventSchema,
  KEY_TONICS,
  normalizeKeyTonic,
  ScoreBarAnchorSchema,
  ScoreBarMapSchema,
  ProjectAssetKindSchema,
  ProjectAssetSchema,
  AudioTrackSchema,
  AudioClipSchema,
  SetlistSchema,
  SetlistItemSchema,
  SetlistProjectItemSchema,
  SetlistBreakItemSchema,
  SETLIST_DEFAULT_TIME_BUDGET_MINUTES,
  PutSetlistBodySchema,
  PatchSetlistAutoAdvanceBodySchema,
  ProjectSchemaV1,
  ProjectSchemaV2,
  ProjectSchemaV3,
  ProjectSchemaV4,
  ProjectSchemaV5,
  ProjectSchema,
  PutProjectBodySchema,
  CreateProjectBodySchema,
  BatchMidiPcBodySchema,
  ExportLibraryBodySchema,
  UpdateProjectBodySchema,
  HealthResponseSchema,
  ApiErrorDetailSchema,
  ApiErrorSchema,
  StageMessageBodySchema,
  ClientHelloMessageSchema,
  TekstClipSchema,
  AkordClipSchema,
  CueClipSchema,
  CueClipRoleSchema,
  type Library,
  type LibraryProjectEntry,
  type FormaClip,
  type TekstClip,
  type AkordClip,
  type CueClip,
  type CueClipRole,
  type ProjectAsset,
  type AudioTrack,
  type AudioClip,
  type Setlist,
  type SetlistItem,
  type SetlistProjectItem,
  type SetlistBreakItem,
  type PutSetlistBody,
  type PatchSetlistAutoAdvanceBody,
  type ProjectV1,
  type ProjectV2,
  type ProjectV3,
  type ProjectV4,
  type ProjectV5,
  type Project,
  type KeySignature,
  type KeyTonic,
  type KeyEvent,
  type ScoreBarAnchor,
  type ScoreBarMap,
  type PutProjectBody,
  type CreateProjectBody,
  type BatchMidiPcBody,
  type ExportLibraryBody,
  type UpdateProjectBody,
  type HealthResponse,
  type ApiErrorDetail,
  type ApiError,
  type StageMessageBody,
  type ClientHelloMessage,
  UpdateStatusSchema,
  ApplyUpdateBodySchema,
  PutServerSettingsBodySchema,
  MidiPortSchema,
  MidiHostConfigSchema,
  PutMidiHostConfigBodySchema,
  MidiHostRatesSchema,
  MidiHostStatusSchema,
  type UpdateStatus,
  type ApplyUpdateBody,
  type PutServerSettingsBody,
  type MidiPort,
  type MidiHostConfig,
  type PutMidiHostConfigBody,
  type MidiHostRates,
  type MidiHostStatus,
} from "./schema.js";

export {
  MIDI_CLOCK_PPQN,
  MIDI_SPP_PER_QUARTER,
  ticksPerMidiClock,
  ticksToMidiClockIndex,
  midiClockIndexToTicks,
  ticksToSpp,
  sppToTicks,
  midiClockIntervalMs,
  elapsedMsToMidiClocks,
} from "./midi-clock.js";

export {
  createProjectV2Seed,
  createProjectV3Seed,
  createProjectV4Seed,
  createProjectV5Seed,
  createDefaultTemplateProject,
  DEFAULT_TEMPLATE_PROJECT_ID,
  createProjectSeed,
  upgradeProjectV1ToV2,
  upgradeProjectV2ToV3,
  upgradeProjectV3ToV4,
  upgradeProjectV4ToV5,
  nextMidiProgramId,
} from "./project-seed.js";

export {
  resolveTempoAt,
  resolveMeterAt,
  resolveKeyAt,
  formatKeySignature,
  resolveFormaClipAt,
} from "./project-resolve.js";

export { ticksToMsAlongTempoMap } from "./tempo-map-ms.js";
export {
  projectEndTicks,
  emptyProjectEndTicks,
} from "./project-bounds.js";

export {
  STAGE_CUE_DEFAULT_LOOKAHEAD_MS,
  resolveStageCueBanner,
  stageCueBannerLabel,
  type StageCueBannerClip,
  type StageCueBannerItem,
  type StageCueBannerPriority,
  type StageCueBannerRole,
  type StageCueBannerSession,
} from "./stage-cue-banner.js";

export {
  defaultSetlist,
  normalizeSetlist,
  pruneSetlistToLibrary,
  resolveSetlistNext,
  buildSetlistView,
  projectIdsFromItems,
  itemsFromProjectIds,
  formatSetDurationMs,
  sumSetlistDurationMs,
  SETLIST_SONG_DURATION_ESTIMATE_MS,
  type SetlistEntry,
  type SetlistView,
  type SetlistViewItem,
} from "./setlist.js";

export { mergePreserveById } from "./merge-preserve.js";

export {
  TimeSignatureSchema,
  TransportStateSchema,
  TransportSeekBodySchema,
  TransportPlayBodySchema,
  TransportLoadBodySchema,
  TransportLoopSchema,
  TransportLoopBodySchema,
  TransportTickMessageSchema,
  StageCueMessageSchema,
  StageCueDismissMessageSchema,
  SessionStageMessageSchema,
  LiveDeskSettingsSchema,
  LiveDeskPatchBodySchema,
  LiveDeskMessageSchema,
  TransportWsServerMessageSchema,
  parseTransportTickPayload,
  DEFAULT_TRANSPORT_BPM,
  DEFAULT_TRANSPORT_METER,
  TRANSPORT_TICK_INTERVAL_MS,
  defaultTransportState,
  transportHomeTicks,
  type TransportHomeSource,
  type TransportState,
  type TransportSeekBody,
  type TransportPlayBody,
  type TransportLoadBody,
  type TransportLoop,
  type TransportLoopBody,
  type TransportTickMessage,
  type StageCueMessage,
  type StageCueDismissMessage,
  type SessionStageMessage,
  type LiveDeskSettings,
  type LiveDeskPatchBody,
  type LiveDeskMessage,
  type TransportWsServerMessage,
} from "./transport.js";

export {
  isUsableLoop,
  normalizeLoop,
  loopWrapTicks,
} from "./transport-loop.js";

export {
  DEFAULT_SCORE_ANCHORS,
  normalizeAnchors,
  normalizeMap,
  songBarToScoreBar,
  logicBarToScoreBar,
  scoreBarToSongBar,
  ticksFromScoreBar,
  type ScoreBarMapLike,
  type ScoreBarToSongBarOptions,
  type NormalizedScoreAnchor,
} from "./score-bar-map.js";

export {
  chordLiteralToSymbolDisplay,
  formatChordForDisplay,
  formatHybridPolishB,
  type ChordDisplayOptions,
} from "./chord-display.js";

export {
  COUNTDOWN_NAME,
  formatSectionNameForDisplay,
  normalizeSectionName,
  type FormatSectionNameOptions,
} from "./section-names.js";

export {
  INSTRUMENT_PITCH_MANUAL_MAX,
  INSTRUMENT_PITCH_MANUAL_MIN,
  INSTRUMENT_PITCH_PRESETS,
  applyInstrumentPitchToChord,
  clampManualInstrumentPitch,
  clampSemitoneOffset,
  isInstrumentPitchMode,
  parseTonicSymbol,
  resolveInstrumentPitchOffset,
  resolveTranspose,
  transposeChord,
  type InstrumentPitchMode,
  type TransposeResolve,
} from "./transpose.js";

export {
  getDisplayTicks,
  wrapDisplayTicks,
  type TransportAnchor,
} from "./soft-clock.js";

export {
  quantizeTicks,
  snapTicksToBarStart,
  snapTicksToBarStartAlongMeterMap,
  snapTicksToBeatGrid,
  snapTicksToBeatGridAlongMeterMap,
  snapTicksToSubdivision,
  DEFAULT_SNAP_MODE,
  type SnapMode,
  type SnapContext,
  type SnapSubdivisionParts,
} from "./snap-grid.js";

export {
  clampFormaSubsections,
  deleteClip,
  insertGapSectionAfterCountdown,
  insertSpanOverwrite,
  moveClipNoOverlap,
  moveClipsRigidDelta,
  moveSectionsFromId,
  placeClipNoOverlap,
  allocateUniqueClipId,
  resizeClipNoOverlap,
  splitClipAt,
  type ClipEdge,
  type CollisionOpts,
  type SplitClipOpts,
} from "./clip-collision.js";

export {
  audioClipAbutGapTicks,
  audioClipBufferOffsetSec,
  audioClipBufferOffsetSecAlongMaps,
  audioClipEndTicks,
  audioClipPlayableMs,
  audioClipRemainingSec,
  audioClipRemainingSecAlongMaps,
  audioFadeGainAtMs,
  applyAbutCrossfade,
  clampAudioClipToAsset,
  clampAudioFades,
  fadeInMsOf,
  fadeOutMsOf,
  findAbutNeighbor,
  gainDbToLinear,
  lengthTicksFromAssetWindow,
  maxAudioLengthTicks,
  resizeAudioClipEnd,
  resizeAudioClipStart,
  trimInMsOf,
  trimOutMsOf,
  type AudioTempoCtx,
} from "./audio-clip.js";

export {
  balanceGains,
  clampFaderGainDb,
  clampPan,
  dbToFaderTaper,
  emptyPeakHold,
  faderTaperToDb,
  FADER_GAIN_FLOOR_DB,
  FADER_TAPER_DB_MAX,
  FADER_TAPER_UNITY_T,
  FADER_TICK_DBS,
  formatFaderTickLabel,
  formatPeakHoldDb,
  isClipPeakDb,
  linearPeakToMeterDb,
  meterDbPeakBand,
  meterDbToUnit,
  METER_DB_MAX,
  METER_DB_MIN,
  PAN_MAX,
  PAN_MIN,
  STEREO_DOWNMIX_LINEAR,
  updatePeakHold,
  type MeterPeakBand,
  type PeakHoldState,
} from "./mixer-math.js";

export {
  DEFAULT_TRACK_COLOR,
  DEFAULT_TRACK_ICON,
  TRACK_COLORS,
  TRACK_ICONS,
  TRACK_ICON_LABELS,
  TrackColorSchema,
  TrackIconSchema,
  resolveTrackColor,
  resolveTrackIcon,
  trackColorForIndex,
  type TrackColor,
  type TrackIcon,
} from "./track-appearance.js";

export {
  AudioBusSchema,
  BusOutputDestSchema,
  ChannelModeSchema,
  MASTER_OUTPUT,
  MAX_AUDIO_BUSSES,
  MixerOutputDestSchema,
  channelModeFromChannelCount,
  isTrackRoutedToBus,
  nextBusName,
  resolveBusOutputDest,
  resolveChannelMode,
  resolveTrackOutputDest,
  type AudioBus,
  type BusOutputDest,
  type ChannelMode,
  type MixerOutputDest,
} from "./mixer-routing.js";

export {
  importUgText,
  sealAkordyLengths,
  chordOnsetsInBar,
  type UgImportErr,
  type UgImportOk,
  type UgImportOptions,
  type UgImportResult,
} from "./ug-import.js";

export {
  placeContentFromForma,
  wandContentToForma,
  type WandMode,
  type WandScope,
  type WandResult,
} from "./wand.js";

export {
  isCountdownDigitClipId,
  countdownDigitLabels,
  syntheticCountdownTekstClips,
  syntheticCountdownAkordClips,
  syntheticCountdownDisplayFromProject,
  scrubCountdownDigitClips,
  regenerateCountdownContent,
  buildCountdownDigitTekstClips,
  type CountdownDigitLabel,
} from "./countdown-content.js";

export {
  migrateLegacySong,
  migrateLegacyDatabase,
  isLegacyCountdownSection,
  parseLegacyMeter,
  legacySongIdToProjectId,
  legacyAssetId,
  mimeForLegacyAsset,
  mapLegacySubsectionOffsets,
  type LegacySong,
  type LegacyDatabase,
  type LegacySection,
  type LegacyPendingAsset,
  type MigrateLegacySongOptions,
  type MigrateLegacySongResult,
  type MigrateLegacyDatabaseResult,
} from "./legacy-migrate.js";

export {
  normalizeSubsectionOffsets,
  subsectionMaxChunkTicks,
  defaultSubsections4Bar,
  hasUsableFormaSubsections,
  ensureFormaSubsections,
} from "./forma-subsections.js";

export {
  detectLibraryImportFormat,
  normalizeLibraryImport,
  looksLikeZipBytes,
  ZIP_IMPORT_UNSUPPORTED_PL,
  type LibraryImportFormat,
  type DetectLibraryImportResult,
  type NormalizeLibraryImportResult,
} from "./library-import.js";
