/**
 * @stagesync/shared — UG / UltraStar import, text-anchor bridge, wand.
 *
 * Explicit named re-exports only (no `export *` from source modules).
 */

export {
  importUgText,
  applyUgImportToProject,
  reflowUgImportSectionBars,
  splitUgSections,
  sealAkordyLengths,
  chordOnsetsInBar,
  type UgImportErr,
  type UgImportOk,
  type UgImportOptions,
  type UgImportResult,
  type UgSectionPreview,
  type SplitUgSectionsOptions,
} from "../ug-import.js";

export {
  importUltrastarText,
  applyUltrastarImportToProject,
  tempoMapWithImportedBpm,
  ultrastarHeaderBpmToMetronome,
  ultrastarBeatToMs,
  suggestGridBpmFromPipeAndFirstVocal,
  ticksPerUltrastarBeat,
  ultrastarBeatToTicks,
  parseUltrastarNoteLine,
  groupUltrastarSyllablesIntoWords,
  stripUltrastarMelisma,
  ultrastarLyricEndsWord,
  ultrastarLyricStartsWord,
  ultrastarSyllableDisplayText,
  ultrastarLineTextFromRawLyrics,
  type UltrastarImportErr,
  type UltrastarImportOk,
  type UltrastarImportOptions,
  type UltrastarImportResult,
  type UltrastarSyllable,
  type UltrastarWord,
  type ApplyUltrastarOptions,
} from "../ultrastar-import.js";

export {
  TEXT_ANCHOR_WEAK_ALIGN,
  DEFAULT_BARS_PER_CHORD,
  DEFAULT_BARS_PER_LINE,
  normalizeLyricToken,
  tokenizeLyrics,
  timedWordsFromUltrastar,
  timedSyllablesFromUltrastar,
  parseChordProLyricLine,
  parseUgBridgeSections,
  isUgBridgeNoiseLine,
  alignWordSequences,
  bridgeUsUgImport,
  bridgeUsUgFromTexts,
  normalizeTekstBlockTimings,
  suggestGridBpmFromUsUgTexts,
  barsPerChordForSection,
  sectionLengthBarsFromUg,
  structuralBarsFromUsWalls,
  freezeFormaContainers,
  buildPristineSectionGrid,
  mapOnsetsIntoContainer,
  interpolateMissingOnsets,
  sectionHasUsSyllables,
  phraseIndicesInSectionWindow,
  chordLineGridOnset,
  evenlySpaceOnsetsOnBarGrid,
  fitOnsetsInContainer,
  enforceMinChordGap,
  placeChordsWithMinGap,
  sealChordLengths,
  quantizeChordOnsets,
  applyUsUgBridgeToProject,
  annotateTekstSourceSections,
  annotateTekstSourceSectionsFromAlign,
  structuralBarOffsetsForChordLines,
  chordTickFromSyllableMs,
  type TimedWord,
  type UgBridgeWord,
  type UgBridgeChord,
  type SectionContainer,
  type TextAnchorBridgeOk,
  type TextAnchorBridgeErr,
  type TextAnchorBridgeResult,
  type TextAnchorBridgeOptions,
  type ApplyUsUgBridgeOptions,
  type FreezeFormaContainersInput,
  type FreezeFormaContainersResult,
  type BuildPristineSectionGridInput,
  type BuildPristineSectionGridResult,
  type PristineSectionChord,
} from "../text-anchor-bridge.js";

export {
  scoreHarmonicAccent,
  findHarmonicAccentSyllable,
  syllablesInChordScope,
  type HarmonicSyllable,
  type HarmonicAccentScoreContext,
} from "../harmonic-accent.js";

export {
  isUgPipeBarLine,
  parseUgPipeBars,
  parseUgPipeBarCells,
  quantizeTicksToBar,
  quantizeTicksToBarOrHalf,
  sectionStartFromVocalTicks,
  ceilTicksToBar,
  floorTicksToBar,
  type UgPipeChordEvent,
  type UgPipeBarsParse,
} from "../ug-pipe-bars.js";

export {
  cleanUgTabContent,
  decodeHtmlEntities,
  isUgAsciiTabLine,
  isUgAuthorNoteLine,
  normalizeUgWikiMarkup,
} from "../ug-content.js";

export {
  UgFetchBodySchema,
  UgFetchResponseSchema,
  UgSearchBodySchema,
  UgSearchHitSchema,
  UgSearchResponseSchema,
  UgTabMetadataSchema,
  type UgFetchBody,
  type UgFetchResponse,
  type UgSearchBody,
  type UgSearchHit,
  type UgSearchResponse,
  type UgTabMetadata,
} from "../ug-api.js";

export {
  UltrastarAccountPutBodySchema,
  UltrastarAccountPutResponseSchema,
  UltrastarAccountStatusSchema,
  UltrastarAccountTestBodySchema,
  UltrastarAccountTestResponseSchema,
  UltrastarFetchBodySchema,
  UltrastarFetchResponseSchema,
  UltrastarSearchBodySchema,
  UltrastarSearchHitSchema,
  UltrastarSearchResponseSchema,
  UltrastarSongMetadataSchema,
  type UltrastarAccountPutBody,
  type UltrastarAccountPutResponse,
  type UltrastarAccountStatus,
  type UltrastarAccountTestBody,
  type UltrastarAccountTestResponse,
  type UltrastarFetchBody,
  type UltrastarFetchResponse,
  type UltrastarSearchBody,
  type UltrastarSearchHit,
  type UltrastarSearchResponse,
  type UltrastarSongMetadata,
} from "../ultrastar-api.js";

export {
  placeContentFromForma,
  type WandMode,
  type WandScope,
  type WandResult,
} from "../wand.js";
