/**
 * @stagesync/shared — Mixer math, track appearance, bus routing.
 *
 * Explicit named re-exports only (no `export *` from source modules).
 */

export {
  advanceMeterBallistics,
  balanceGains,
  clampFaderGainDb,
  clampPan,
  dbToFaderTaper,
  emptyPeakHold,
  faderTaperToDb,
  FADER_GAIN_FLOOR_DB,
  FADER_TAPER_DB_MAX,
  FADER_TAPER_UNITY_T,
  FADER_TICK_DBS,
  formatFaderTickLabel,
  formatPeakHoldDb,
  isClipPeakDb,
  linearPeakToMeterDb,
  meterDbPeakBand,
  meterDbToUnit,
  METER_ATTACK_SEC,
  METER_BAND_CLIP_DB,
  METER_BAND_WARN_DB,
  METER_DB_MAX,
  METER_DB_MIN,
  METER_RELEASE_SEC,
  PAN_MAX,
  PAN_MIN,
  STEREO_DOWNMIX_LINEAR,
  updatePeakHold,
  type MeterPeakBand,
  type PeakHoldState,
} from "../mixer/mixer-math.js";

export {
  DEFAULT_TRACK_COLOR,
  DEFAULT_TRACK_ICON,
  TRACK_COLORS,
  TRACK_ICONS,
  TRACK_ICON_LABELS,
  TrackColorSchema,
  TrackIconSchema,
  resolveTrackColor,
  resolveTrackIcon,
  trackColorForIndex,
  type TrackColor,
  type TrackIcon,
} from "../ui-helpers/track-appearance.js";

export {
  AudioBusSchema,
  AudioHardwareOutputSchema,
  HwOutputPatchSchema,
  BusOutputDestSchema,
  ChannelModeSchema,
  MASTER_OUTPUT,
  MAX_AUDIO_BUSSES,
  MAX_AUDIO_HARDWARE_OUTPUTS,
  MasterOutputRoutingSchema,
  MixerOutputDestSchema,
  busGraphHasCycle,
  channelModeFromChannelCount,
  channelRangeOccupied,
  channelRangesOverlap,
  hardwarePatchChannelWidth,
  hwOutputUiAllowed,
  isHwOutRepatchBlockedWhilePlaying,
  isTrackRoutedToBus,
  listMasterStereoPairOptions,
  masterOutputOverlapsHwPatches,
  nextBusName,
  resolveBusOutputDest,
  resolveChannelMode,
  resolveMasterOutputRouting,
  resolveTrackOutputDest,
  wouldCreateBusCycle,
  type AudioBus,
  type AudioHardwareOutput,
  type HwOutputPatch,
  type BusEdge,
  type BusOutputDest,
  type ChannelMode,
  type MasterOutputRouting,
  type MixerOutputDest,
} from "../mixer/mixer-routing.js";
