/**
 * @stagesync/shared — Zod schemas and project/protocol types.
 *
 * Explicit named re-exports only (no `export *` from source modules).
 */

export {
  LibrarySchema,
  LibraryProjectEntrySchema,
  BPM_MIN,
  BPM_MAX,
  BpmSchema,
  ProjectIdSchema,
  FormaClipKindSchema,
  FormaClipSchema,
  TempoEventSchema,
  MeterEventSchema,
  KeySignatureSchema,
  KeyEventSchema,
  KEY_TONICS,
  normalizeKeyTonic,
  ScoreBarAnchorSchema,
  ScoreBarMapSchema,
  ProjectAssetKindSchema,
  ProjectAssetSchema,
  AudioTrackSchema,
  AudioClipSchema,
  SetlistSchema,
  SetlistItemSchema,
  SetlistProjectItemSchema,
  SetlistBreakItemSchema,
  SETLIST_DEFAULT_TIME_BUDGET_MINUTES,
  PutSetlistBodySchema,
  PatchSetlistAutoAdvanceBodySchema,
  ProjectSchemaV1,
  ProjectSchemaV2,
  ProjectSchemaV3,
  ProjectSchemaV4,
  ProjectSchemaV5,
  ProjectSchemaV6,
  ProjectSchema,
  PutProjectBodySchema,
  CreateProjectBodySchema,
  BatchMidiPcBodySchema,
  ExportLibraryBodySchema,
  UpdateProjectBodySchema,
  PROTOCOL_VERSION,
  HealthResponseSchema,
  UiManifestAssetSchema,
  UiManifestSchema,
  UiHashFileSchema,
  ApiErrorDetailSchema,
  ApiErrorSchema,
  StageMessageBodySchema,
  ClientHelloMessageSchema,
  TekstClipLineSchema,
  TekstBlockRoleSchema,
  TekstBlockSchema,
  TekstClipSchema,
  MelodyNoteClipSchema,
  AkordClipSchema,
  CueClipSchema,
  CueClipRoleSchema,
  CueSampleConfigSchema,
  CueSampleOutputSchema,
  type Library,
  type LibraryProjectEntry,
  type FormaClip,
  type TekstClipLine,
  type TekstBlockRole,
  type TekstBlock,
  type TekstClip,
  type MelodyNoteClip,
  type AkordClip,
  type CueClip,
  type CueClipRole,
  type CueSampleConfig,
  type CueSampleOutput,
  type ProjectAsset,
  type AudioTrack,
  type AudioClip,
  type Setlist,
  type SetlistItem,
  type SetlistProjectItem,
  type SetlistBreakItem,
  type PutSetlistBody,
  type PatchSetlistAutoAdvanceBody,
  type ProjectV1,
  type ProjectV2,
  type ProjectV3,
  type ProjectV4,
  type ProjectV5,
  type ProjectV6,
  type Project,
  type TempoEvent,
  type MeterEvent,
  type KeySignature,
  type KeyTonic,
  type KeyEvent,
  type ScoreBarAnchor,
  type ScoreBarMap,
  type PutProjectBody,
  type CreateProjectBody,
  type BatchMidiPcBody,
  type ExportLibraryBody,
  type UpdateProjectBody,
  type HealthResponse,
  type UiManifestAsset,
  type UiManifest,
  type UiHashFile,
  type ApiErrorDetail,
  type ApiError,
  type StageMessageBody,
  type ClientHelloMessage,
  UpdateStatusSchema,
  ApplyUpdateBodySchema,
  RestoreBackupBodySchema,
  PutServerSettingsBodySchema,
  PushPlatformSchema,
  PushChannelSchema,
  PushTokenRegisterBodySchema,
  PushTokenUnregisterBodySchema,
  PushPublicConfigSchema,
  MidiPortSchema,
  MidiChannelSchema,
  MidiHostConfigSchema,
  PutMidiHostConfigBodySchema,
  MidiHostRatesSchema,
  MidiHostStatusSchema,
  type UpdateStatus,
  type ApplyUpdateBody,
  type RestoreBackupBody,
  type PutServerSettingsBody,
  type PushPlatform,
  type PushChannel,
  type PushTokenRegisterBody,
  type PushTokenUnregisterBody,
  type PushPublicConfig,
  type MidiPort,
  type MidiHostConfig,
  type PutMidiHostConfigBody,
  type MidiHostRates,
  type MidiHostStatus,
  HEXSPEAK,
  type HexspeakKey,
} from "../project/schema.js";
