/**
 * @stagesync/shared — Tempo map, MultiPass solver, Smart Tempo.
 *
 * Explicit named re-exports only (no `export *` from source modules).
 */

export {
  ticksToMsAlongTempoMap,
  ticksToSeconds,
  secondsToTicks,
  ticksToSecondsAlongMap,
  secondsToTicksAlongMap,
  advanceTicksAlongTempoMap,
  type TempoMapEventLike,
  type MeterMapEventLike,
  type TempoMapProject,
} from "../tempo-map.js";

export {
  TEMPO_SOLVER_HIGH_WEIGHT,
  TEMPO_SOLVER_SECTION_WEIGHT,
  TEMPO_SOLVER_CHORD_WEIGHT,
  TEMPO_SOLVER_SYLLABLE_WEIGHT,
  TEMPO_SOLVER_PRUNE_DELTA_BPM,
  TEMPO_SOLVER_MAX_STEP_RATIO,
  TEMPO_SOLVER_SEED_METRO_MAX_RATIO,
  TEMPO_SOLVER_ANACRUSIS_MAX_BARS,
  TEMPO_MAP_MIN_BPM,
  TEMPO_MAP_MAX_BPM,
  weightForTempoAnchorKind,
  computeSeedBpmFromAnchors,
  applySeedMetronomeFallback,
  isTickOnBarOrHalf,
  softClampBpmToSeed,
  softClampBpmAdjacent,
  thinMsTickAnchors,
  isAnacrusisMs,
  sectionBeat1Ms,
  sectionBeat1MsFromVocalMs,
  pristineBarsFromMsSpan,
  resolveAnchorTargetTicks,
  tempoEventsFromMsTickAnchors,
  runMultiPassTempoSolver,
  anacrusisPickupBarsBeforeSection,
  layoutContiguousFormaPlans,
  type TempoAnchorKind,
  type TempoSolverAnchor,
  type TempoSolverSectionPlan,
  type MultiPassTempoSolverInput,
  type MultiPassTempoSolverResult,
  type MsTickAnchor,
} from "../tempo-map-solver.js";

export {
  US_UG_BACKING_TRACK_NAME,
  US_UG_BACKING_TRACK_ID,
  US_UG_BACKING_CLIP_ID,
  YOUTUBE_VIDEO_ID_RE,
  SMART_TEMPO_SPARSE_MIN_BPM_DELTA,
  SMART_TEMPO_SPARSE_WINDOW_BEATS,
  SMART_TEMPO_SPARSE_MIN_BAR_GAP,
  SMART_TEMPO_SPARSE_MAX_BPM_STEP,
  extractYoutubeVideoId,
  msPerBarAtBpm,
  suggestBeat1MsFromPipeAndGap,
  snapBeat1MsToOnset,
  alignBeat1ToChordSyllable,
  extendBeatGridToDuration,
  evaluateDriftGate,
  snapMsToNearestBeat,
  refineBeatGridWithOnsets,
  medianBpmFromBeatMs,
  rescaleBeatGridToBpm,
  sanitizeBeatGridIbis,
  selfConsistentScaleBeatGrid,
  preferAudioTempoSeed,
  preferEditorialTempoSeed,
  sparsifyTempoNodesFromBeatGrid,
  pruneTempoMapByBpmDelta,
  tempoNodesFromBeatGrid,
  tempoNodesAtBarBoundaries,
  beatGridToContentEpoch,
  tempoNodesToContentEpoch,
  tempoNodesToFileEpoch,
  runAudioDrivenSmartTempo,
  layoutFormaFromUgBarCounts,
  layoutFormaFromAlignedWords,
  tempoMapFromTempoNodes,
  tempoNodesFromSectionPlans,
  placeUsUgBackingAudioClip,
  audioDurationOverflowWarning,
  type SmartTempoAudioRef,
  type AudioAnalysisResult,
  type TempoNode,
  type DriftGateResult,
  type AudioSmartTempoInput,
  type AudioSmartTempoResult,
  type UgFormaSectionInput,
  type AlignedWordFormaSection,
  type PlaceUsUgBackingAudioOpts,
  type SparsifyTempoNodesOptions,
} from "../smart-tempo.js";
